version: '3.4'
services:
    web:
        build: .
        container_name: "web"
        expose:
            - "5000"
        ports:
            - "5000:5000"
        volumes:
            - .:/python_flask
        #depends_on:
            #- redis
    #redis:
        #image: redis